FROM python:3.8
#6-alpine3.9 
#culibraries/celery:1.0.4
# python:3.6-alpine3.9

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 PYTHONUNBUFFERED=1 

RUN apt update
# RUN RUN apt-get update && apt-get install -y \
#     git \
#     imagemagick \
#     libimage-exiftool-perl \
#     libtiff-dev \
#     libxml2-dev \
#     libxslt-dev \
#     libopenjp2-7 
# mariadb-server
RUN apt install -y  git tzdata vim python3-pil python3-pil.imagetk
RUN apt install -y default-libmysqlclient-dev
# RUN apk add build-base libressl libffi-dev libressl-dev libxslt-dev libxml2-dev xmlsec-dev xmlsec
# RUN apk add mariadb-dev git tzdata
RUN cp /usr/share/zoneinfo/America/Denver /etc/localtime

WORKDIR /  
COPY requirements.txt ./  
RUN pip install --no-cache-dir -r requirements.txt  
RUN rm requirements.txt  


COPY . /app  
WORKDIR /app

#Setup Celery User
#Setup Celery User
RUN useradd -r -U -m celery \
  && chown celery:celery -R /app

#USER celery

CMD ["/app/startCeleryWorker"]
