#!/usr/bin/env python3

import os
from subprocess import call
from celeryconfig import *

for itm in os.environ.get("CELERY_SOURCE").split(','):
    call(['pip3','install',itm])

call(['pip3','install','Pillow'])

celery_queue=os.environ.get("CELERY_QUEUE","celery")
log_level=os.environ.get("LOG_LEVEL","INFO")

call(["su", "-p", "celery", "-c",
  "celery -Q {0} -l {1} worker".format(celery_queue, log_level)])
#call(["celery", "worker", "-Q", celery_queue, "-l", log_level])